SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS Pet;
DROP TABLE IF EXISTS Telefone;
DROP TABLE IF EXISTS Coleta_Usuario;
DROP TABLE IF EXISTS Pontos_Usuario;
DROP TABLE IF EXISTS Pontos_Coleta;
DROP TABLE IF EXISTS Empresa_Produto;
DROP TABLE IF EXISTS Produto;
DROP TABLE IF EXISTS Troca_Usuario;
DROP TABLE IF EXISTS Troca;
DROP TABLE IF EXISTS Endereco; 
DROP TABLE IF EXISTS Coleta;
DROP TABLE IF EXISTS Pontos;
DROP TABLE IF EXISTS Empresa;
DROP TABLE IF EXISTS Usuario; 


SET FOREIGN_KEY_CHECKS = 1;